require:
  - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.3.0
  Include:
     - config/initializers/*

Capybara/VisibilityMatcher:
  Enabled: false

Documentation:
  Enabled: false

Layout/HashAlignment:
  Enabled: false
Layout/LineLength:
  Max: 120
Layout/MultilineMethodCallIndentation:
  EnforcedStyle: aligned
Lint/AmbiguousBlockAssociation:
  Exclude:
    - spec/**/*
Lint/IneffectiveAccessModifier:
  Enabled: false
Lint/MissingSuper:
  Enabled: false
Lint/RedundantSplatExpansion:
  Enabled: false
Lint/UriEscapeUnescape:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Metrics/ClassLength:
  Max: 500
Metrics/ModuleLength:
  Max: 250
  Exclude:
    - spec/**/*
Naming/AccessorMethodName:
  Enabled: false
Naming/BlockForwarding:
  Enabled: false
Naming/InclusiveLanguage:
  Enabled: false
Naming/FileName:
  Enabled: false
Naming/MemoizedInstanceVariableName:
  Enabled: false
Naming/PredicateName:
  Enabled: false
Naming/VariableNumber:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/ExponentialNotation:
  Enabled: false
Style/FetchEnvVar:
  Enabled: true
  Exclude:
    - spec/**/*
Style/FormatString:
  Enabled: false
Style/FormatStringToken:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/HashSyntax:
  EnforcedStyle: ruby19
Style/InPatternThen:
  Enabled: false
Style/MultilineInPatternThen:
  Enabled: false
Style/MapToHash:
  Enabled: false
Style/NumericLiteralPrefix:
  Enabled: false
Style/NumericPredicate:
  Enabled: false
Style/OpenStructUse:
  Enabled: false
Style/SafeNavigation:
  Enabled: false
Style/StringLiterals:
  EnforcedStyle: double_quotes
Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma
Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

RSpec/AnyInstance:
  Enabled: false
RSpec/ChangeByZero:
  Enabled: false
RSpec/ContextWording:
  Enabled: false
RSpec/DescribedClass:
  Enabled: false
RSpec/DescribeClass:
  Enabled: false
RSpec/ExampleLength:
  Enabled: false
RSpec/ExampleWording:
  Enabled: false
RSpec/ExpectInHook:
  Enabled: false
RSpec/HooksBeforeExamples:
  Enabled: false
RSpec/ImplicitBlockExpectation:
  Enabled: false
RSpec/InstanceVariable:
  Exclude:
    - spec/views/**/*
RSpec/LetBeforeExamples:
  Enabled: false
RSpec/LetSetup:
  Enabled: false
RSpec/MessageChain:
  Enabled: false
RSpec/MessageSpies:
  Enabled: false
RSpec/MultipleDescribes:
  Enabled: false
RSpec/MultipleExpectations:
  Enabled: false
RSpec/MultipleMemoizedHelpers:
  Enabled: false
RSpec/NamedSubject:
  Enabled: false
RSpec/NestedGroups:
  Enabled: false
RSpec/RepeatedDescription:
  Enabled: false
RSpec/RepeatedExampleGroupBody:
  Enabled: false
RSpec/RepeatedExampleGroupDescription:
  Enabled: false
RSpec/StubbedMock:
  Enabled: false
RSpec/VerifiedDoubles:
  Enabled: false
RSpec/VerifiedDoubleReference:
  Enabled: false
