version: 2.1

orbs:
  slack: circleci/slack@4.4.4

jobs:
  build:
    docker:
      - image: cimg/ruby:3.3.0

    steps:
      - slack/notify:
          channel: $SLACK_DEFAULT_CHANNEL
          token: $SLACK_ACCESS_TOKEN
          event: always
          context: CircleCI

      - checkout
      - run:
          name: Install dependencies
          command: |
            gem install bundler
            bundle install --jobs=4 --retry=3
      - run:
          name: RuboCop
          command: |
            bundle exec rubocop
      - run:
          name: RSpec
          command: |
            bundle exec rspec

workflows:
  version: 2
  build:
    jobs:
      - build
      