orbs:
  slack: circleci/slack@4.4.4

version: 2.1

jobs:
  build:
    docker:
      - image: cimg/ruby:3.3.0

    steps:
      - checkout
      - slack/notify:
          channel: C06K11FAQ48 
          event: always 
          ignore_errors: true 

      - run:
          name: Install dependencies
          command: |
            gem install bundler
            bundle install --jobs=4 --retry=3

      - run:
          name: RuboCop
          command: |
            bundle exec rubocop

      - run:
          name: RSpec
          command: |
            bundle exec rspec

workflows:
  version: 2
  build:
    jobs:
      - build
