version: 2.1

orbs:
  slack: circleci/slack@4.4.4

jobs:
  build:
    docker:
      - image: cimg/ruby:3.3.0
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            gem install bundler
            bundle install --jobs=4 --retry=3
      - run:
          name: RuboCop
          command: |
            bundle exec rubocop
      - run:
          name: RSpec
          command: |
            bundle exec rspec

  notification:
    docker:
      - image: cimg/ruby:3.3.0
    steps:    
      - slack/notify:
          channel: $SLACK_DEFAULT_CHANNEL 
          event: fail
          template: basic_fail_1
          mentions: <@SLACK_USER_ID>

      - slack/notify:
          channel: $SLACK_DEFAULT_CHANNEL 
          event: pass
          template: success_tagged_deploy_1
          mentions: <@SLACK_USER_ID>

workflows:
  version: 2
  build_and_notify:
    jobs:
      - build
      - notification:
          context: CircleCI
          requires:
            - build
