version: 2.1

jobs:
  build:
    docker:
      - image: cimg/ruby:3.3.0

    steps:
      - checkout

      - run:
          name: Install dependencies
          command: |
            gem install bundler
            bundle install --jobs=4 --retry=3

      - run:
          name: Run RuboCop
          command: |
            bundle exec rubocop

      - run:
          name: Run RSpec tests
          command: |
            bundle exec rspec

workflows:
  version: 2
  build:
    jobs:
      - build
